#!/bin/sh
#
# @name omniHex SITL
#
# @type Hexarotor x
# @class Copter
#
# @maintainer Yueqian Liu <yueqianliu@outlook.com>
#

. ${R}etc/init.d/rc.mc_defaults

# EKF2 settings
param set-default EKF2_AID_MASK 280
param set-default EKF2_HGT_MODE 3
param set-default EKF2_EV_DELAY 5

#########################################################################
###################### BELOW SHOULD BE USED WITH ########################
################ make px4_sitl_ctrlalloc gazebo_omni_hex ################
#################### for omni configuration flight ######################
#########################################################################

# control allocation data flow
angular_velocity_controller start
control_allocator start
param set MPC_USE_HTE 0
param set COM_PREARM_MODE 0

# model inertia (kg, m, relative to PX4 convention body frame)
# inertia taken at the centre of mass aligned with px4 body frame
param set-default VM_MASS 4       # 3.814
param set-default VM_INERTIA_XX 0.08401764152
param set-default VM_INERTIA_XY -0.00000445135
param set-default VM_INERTIA_XZ 0.00014163105 
param set-default VM_INERTIA_YY 0.08169689992
param set-default VM_INERTIA_YZ -0.00000936372
param set-default VM_INERTIA_ZZ 0.14273598018
param set-default VM_COM_X 0
param set-default VM_COM_Y 0
param set-default VM_COM_Z 0.03

# position controller
param set-default MPC_XY_P 6            # 0.95
param set-default MPC_XY_VEL_P_ACC 1.8    # 1.8
param set-default MPC_XY_VEL_I_ACC 0.4    # 0.4
param set-default MPC_XY_VEL_D_ACC 0.2    # 0.2
#param set-default MPC_XY_VEL_MAX 100
param set-default MPC_Z_P 6            # 1
param set-default MPC_Z_VEL_P_ACC 4     # 4
param set-default MPC_Z_VEL_I_ACC 2     # 2
param set-default MPC_Z_VEL_D_ACC 0     # 0
#param set-default MPC_Z_VEL_MAX_UP 20
#param set-default MPC_Z_VEL_MAX_DN 5


# attitude controller
param set-default MC_ROLL_P 12         # 6.5
param set-default MC_PITCH_P 12        # 6.5
param set-default MC_YAW_P 3          # 2.8
param set-default MC_ROLLRATE_MAX 60
param set-default MC_PITCHRATE_MAX 60
param set-default MC_YAWRATE_MAX 60

# angular velocity controller settings
param set-default AVC_X_P 18             # 18
param set-default AVC_X_I 0.3           # 0.2
param set-default AVC_X_D 0.01          # 0.36
param set-default AVC_Y_P 18             # 18
param set-default AVC_Y_I 0.3           # 0.2
param set-default AVC_Y_D 0.01          # 0.36
param set-default AVC_Z_P 8             # 7
param set-default AVC_Z_I 0.3           # 0.1
param set-default AVC_Z_D 0.01          # 0

# acro mode
param set-default MPC_MAN_R_MAX 40
param set-default MPC_MAN_P_MAX 40
param set-default MPC_MAN_Y_MAX 40

# preflight
param set-default COM_DISARM_PRFLT 10

# control allocator settings
param set-default CA_AIRFRAME 3
param set-default CA_METHOD 2

param set-default CA_ACT0_MIN 0.0
param set-default CA_ACT1_MIN 0.0
param set-default CA_ACT2_MIN 0.0
param set-default CA_ACT3_MIN 0.0
param set-default CA_ACT4_MIN 0.0
param set-default CA_ACT5_MIN 0.0
param set-default CA_ACT6_MIN 0.0
param set-default CA_ACT7_MIN 0.0
param set-default CA_ACT8_MIN 0.0
param set-default CA_ACT9_MIN 0.0
param set-default CA_ACT10_MIN 0.0
param set-default CA_ACT11_MIN 0.0
param set-default CA_ACT12_MIN 0.0
param set-default CA_ACT13_MIN 0.0
param set-default CA_ACT14_MIN 0.0
param set-default CA_ACT15_MIN 0.0

param set-default CA_ACT0_MAX 1.0
param set-default CA_ACT1_MAX 1.0
param set-default CA_ACT2_MAX 1.0
param set-default CA_ACT3_MAX 1.0
param set-default CA_ACT4_MAX 1.0
param set-default CA_ACT5_MAX 1.0
param set-default CA_ACT6_MAX 1.0
param set-default CA_ACT7_MAX 1.0
param set-default CA_ACT8_MAX 1.0
param set-default CA_ACT9_MAX 1.0
param set-default CA_ACT10_MAX 1.0
param set-default CA_ACT11_MAX 1.0
param set-default CA_ACT12_MAX 1.0
param set-default CA_ACT13_MAX 1.0
param set-default CA_ACT14_MAX 1.0
param set-default CA_ACT15_MAX 1.0

param set-default CA_OH_AL 0.340        # allocation matrix param
param set-default CA_OH_CT 19.125
param set-default CA_OH_KT 1.1475

param set-default CA_OH_DEBUG_EN 0
param set-default CA_OH_ROTATE_DIR 0
param set-default CA_OH_ARM_D_MAX 0.03
param set-default CA_OH_FORCE_THR 10

param set-default CA_OH_DAMP_THR 0.3    # kinematic singularity
param set-default CA_OH_ALGN_THR 0.1

# mixer settings
set MAV_TYPE 13
set MIXER omnihex
set PWM_OUT 123456
set MIXER_AUX omnihex_aux
set PWM_AUX_OUT 123456
#########################################################################
###################### BELOW SHOULD BE USED WITH ########################
############# make px4_sitl gazebo_omni_hex (no _ctrlalloc) #############
################## for fixed arm underactuated flight ###################
#########################################################################

# param set-default MC_PITCHRATE_P 0.1
# param set-default MC_PITCHRATE_I 0.05
# param set-default MC_PITCH_P 6.0
# param set-default MC_ROLLRATE_P 0.15
# param set-default MC_ROLLRATE_I 0.1
# param set-default MC_ROLL_P 6.0
# param set-default MPC_XY_VEL_I_ACC 4
# param set-default MPC_XY_VEL_P_ACC 3

# param set-default RTL_DESCEND_ALT 10

# param set-default TRIG_INTERFACE 3
# param set-default TRIG_MODE 4
# param set-default MNT_MODE_IN 4
# param set-default MNT_DO_STAB 2

# set MAV_TYPE 13

# set MIXER hexa_x
