#!/bin/sh
#
# @name Omni Hex
#
# @type Hexarotor x
# @class Copter
#
# @maintainer Yueqian Liu
#
# @board px4_fmu-v2 exclude
#

. ${R}etc/init.d/rc.mc_defaults

#####################################################################
#     RTPS comm will be started automatically if params are set     #
#####################################################################
param set-default RTPS_CONFIG 101
param set-default MAV_0_CONFIG 0
param set-default SER_TEL1_BAUD 3000000

#####################################################################
#                          EKF2 settings                            #
#####################################################################
param set-default EKF2_AID_MASK 88
param set-default EKF2_HGT_MODE 3
param set-default EKF2_EV_DELAY 5
param set-default EKF2_EV_POS_X 0
param set-defualt EKF2_EV_POS_Y 0
param set-default EKF2_EV_POS_Z -0.072

#####################################################################
#                   control allocation data flow                    #
#####################################################################
angular_velocity_controller start
control_allocator start
param set MPC_USE_HTE 0
param set COM_PREARM_MODE 0

#####################################################################
##   model inertia (kg, m, relative to PX4 convention body frame)  ##
## inertia taken at the centre of mass aligned with px4 body frame ##
#####################################################################
param set-default VM_MASS 4       # 3.814
param set-default VM_INERTIA_XX 0.08401764152
param set-default VM_INERTIA_XY -0.00000445135
param set-default VM_INERTIA_XZ 0.00014163105 
param set-default VM_INERTIA_YY 0.08169689992
param set-default VM_INERTIA_YZ -0.00000936372
param set-default VM_INERTIA_ZZ 0.14273598018
param set-default VM_COM_X 0
param set-default VM_COM_Y 0
param set-default VM_COM_Z 0.03

#####################################################################
#                       position controller                         #
#####################################################################
param set-default MPC_XY_P 0.95            # 0.95
param set-default MPC_XY_VEL_P_ACC 1.8    # 1.8
param set-default MPC_XY_VEL_I_ACC 0.4    # 0.4
param set-default MPC_XY_VEL_D_ACC 0.2    # 0.2
#param set-default MPC_XY_VEL_MAX 100
param set-default MPC_Z_P 1            # 1
param set-default MPC_Z_VEL_P_ACC 4     # 4
param set-default MPC_Z_VEL_I_ACC 2     # 2
param set-default MPC_Z_VEL_D_ACC 0     # 0
#param set-default MPC_Z_VEL_MAX_UP 20
#param set-default MPC_Z_VEL_MAX_DN 5

#####################################################################
#                        attitude controller                        #
#####################################################################
param set-default MC_ROLL_P 6.5         # 6.5
param set-default MC_PITCH_P 6.5        # 6.5
param set-default MC_YAW_P 2.8          # 2.8
param set-default MC_ROLLRATE_MAX 50
param set-default MC_PITCHRATE_MAX 50
param set-default MC_YAWRATE_MAX 50

#####################################################################
#                  angular velocity controller settings             #
#####################################################################
param set-default AVC_X_P 8             # 18
param set-default AVC_X_I 0.3           # 0.2
param set-default AVC_X_D 0.01          # 0.36
param set-default AVC_Y_P 8             # 18
param set-default AVC_Y_I 0.3           # 0.2
param set-default AVC_Y_D 0.01          # 0.36
param set-default AVC_Z_P 4             # 7
param set-default AVC_Z_I 0.3           # 0.1
param set-default AVC_Z_D 0.01          # 0

#####################################################################
#                             acro mode                             #
#####################################################################
param set-default MPC_MAN_R_MAX 40
param set-default MPC_MAN_P_MAX 40
param set-default MPC_MAN_Y_MAX 40

#####################################################################
#                     control allocator settings                    #
#####################################################################
param set-default CA_AIRFRAME 3
param set-default CA_METHOD 2

param set-default CA_ACT0_MIN 0.0
param set-default CA_ACT1_MIN 0.0
param set-default CA_ACT2_MIN 0.0
param set-default CA_ACT3_MIN 0.0
param set-default CA_ACT4_MIN 0.0
param set-default CA_ACT5_MIN 0.0
param set-default CA_ACT6_MIN 0.0
param set-default CA_ACT7_MIN 0.0
param set-default CA_ACT8_MIN 0.0
param set-default CA_ACT9_MIN 0.0
param set-default CA_ACT10_MIN 0.0
param set-default CA_ACT11_MIN 0.0

param set-default CA_ACT0_MAX 1.0
param set-default CA_ACT1_MAX 1.0
param set-default CA_ACT2_MAX 1.0
param set-default CA_ACT3_MAX 1.0
param set-default CA_ACT4_MAX 1.0
param set-default CA_ACT5_MAX 1.0
param set-default CA_ACT6_MAX 1.0
param set-default CA_ACT7_MAX 1.0
param set-default CA_ACT8_MAX 1.0
param set-default CA_ACT9_MAX 1.0
param set-default CA_ACT10_MAX 1.0
param set-default CA_ACT11_MAX 1.0

param set-default CA_OH_AL 0.340        # allocation matrix param
param set-default CA_OH_CT 19.125
param set-default CA_OH_KT 1.1475

param set-default CA_OH_DEBUG_EN 0
param set-default CA_OH_ROTATE_DIR 0
param set-default CA_OH_ARM_D_MAX 0.03
param set-default CA_OH_FORCE_THR 10

param set-default CA_OH_DAMP_THR 0.3    # kinematic singularity
param set-default CA_OH_ALGN_THR 0.1

#####################################################################
#                          mixer settings                           #
#####################################################################
set MAV_TYPE 13
set MIXER direct
set PWM_OUT 123456

#####################################################################
#                           other settings                          #
#####################################################################
param set-default CBRK_IO_SAFETY 22027
param set-default CBRK_AIRSPD_CHK 162128
param set-default CBRK_SUPPLY_CHK 894281 
param set-default CBRK_USB_CHK 197848
param set-default COM_DISARM_PRFLT 10
